[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
if = "!has('mac')"
hook_add = '''
  augroup MyColor
    autocmd!
    autocmd VimEnter * nested colorscheme iceberg
  augroup END
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline/vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_linters = {
  \   'python': ['flake8'],
  \   'go': ['goimports', 'go mod', 'go vet', 'gotype', 'gosimple', 'golangserver', 'golangci-lint'],
  \ }
  let g:ale_fix_on_save = 1
  let g:ale_echo_msg_error_str = 'E'
  let g:ale_echo_msg_warning_str = 'W'
  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
  let g:ale_open_list = 1
  let g:ale_lint_on_save = 1
  let g:ale_lint_on_text_changed = 0
  let g:ale_set_loclist = 0
  let g:ale_set_quickfix = 0
'''

[[plugins]]
repo = 'guns/xterm-color-table.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_char = '¦'
  let g:indentLine_color_term = 236
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
  let g:go_fmt_command = "goimports"
'''

[[plugins]]
repo = 'hashivim/vim-terraform'
hook_add = '''
  let g:terraform_fmt_on_save = 1
  let g:terraform_align = 1
  let g:terraform_fold_section = 1
'''

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = 'haskell'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = 'haskell'

[[plugins]]
repo = 'alx741/vim-stylishask'
on_ft = 'haskell'
hook_add = '''
  let g:stylishask_config_file = '~/.stylish-haskell.yaml'
'''

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

[[plugins]]
repo = 'purescript-contrib/purescript-vim'
on_ft = 'purescript'
