#!/bin/bash

title="$1"
message="$2"

# Find powershell.exe: check PATH first, then known locations
if command -v powershell.exe &>/dev/null; then
  POWERSHELL="powershell.exe"
elif [ -x "/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" ]; then
  POWERSHELL="/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe"
else
  exit 1
fi

"$POWERSHELL" -c "(New-Object Media.SoundPlayer 'C:\\Windows\\Media\\tada.wav').PlaySync()"

"$POWERSHELL" -Command "[reflection.assembly]::loadwithpartialname('System.Windows.Forms'); \$notify = new-object system.windows.forms.notifyicon; \$notify.icon = [System.Drawing.SystemIcons]::Information; \$notify.visible = \$true; \$notify.showballoontip(10,'${title}','${message}',[system.windows.forms.tooltipicon]::Info)"
