name: Pull Request Checks

on:
  pull_request:

permissions: {}

jobs:
  common-checks:
    name: Common Checks
    permissions:
      contents: read
      pull-requests: read
    # TODO: repin to the next release tag once nownabe/workflows#24 is released
    uses: nownabe/workflows/.github/workflows/pr.yaml@259f29852b37df48a6a88aa911740928206828a5 # nownabe/workflows#24

  result:
    name: Pull Request Checks
    if: always()
    needs:
      - common-checks
    runs-on: ubuntu-slim
    timeout-minutes: 5
    permissions: {}
    steps:
      - name: Check job results
        env:
          HAS_FAILURE: ${{ contains(needs.*.result, 'failure') }}
          HAS_CANCELLED: ${{ contains(needs.*.result, 'cancelled') }}
        run: '[[ "$HAS_FAILURE" == "false" && "$HAS_CANCELLED" == "false" ]]'
