name: Pull Request Checks

on:
  pull_request:

permissions: {}

jobs:
  common-checks:
    name: Common Checks
    permissions:
      contents: read
      pull-requests: read
    uses: nownabe/workflows/.github/workflows/pr.yaml@0f93400a7e95e1f9637bab89640ba22c1bdd8af3 # v2.0.0

  nix-build:
    name: Nix Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: experimental-features = nix-command flakes
      - name: Build home configurations
        run: |
          nix build --no-link --print-build-logs \
            .#homeConfigurations.wsl.activationPackage \
            .#homeConfigurations.linux.activationPackage

  result:
    name: Pull Request Checks
    if: always()
    needs:
      - common-checks
      - nix-build
    runs-on: ubuntu-slim
    timeout-minutes: 5
    permissions: {}
    steps:
      - name: Check job results
        env:
          HAS_FAILURE: ${{ contains(needs.*.result, 'failure') }}
          HAS_CANCELLED: ${{ contains(needs.*.result, 'cancelled') }}
        run: '[[ "$HAS_FAILURE" == "false" && "$HAS_CANCELLED" == "false" ]]'
